Spider:
  # eid与fp可以用浏览器打开TEST目录下的get_eid_fp.html获取
  eid: "2PBCMB2WINZUQI6XRDCSKOZXTCHEOHLDABNAVSAEYTS6DBH2DWOACQPUEKXGHV7ZYTKCRDXZX34SPL2XI3KQYVNVSM"
  fp: "63a2c6fceb97a082753cdf00710f4f46"
  # area到area_id目录下人工查找，例如：江西省南昌市昌北区蛟桥镇的area是21_1827_4101_40925
  area: "21_1827_4101_40925"
  # 商品id
  sku_id: "100021890778"
  # 购买数量
  amount: 1
  # 设定时间 # 2020-12-09 10:00:00.100000（修改成每天的几点几分几秒几毫秒）
  buy_time: "2021-11-13 04:30:00.000"
  # 提交订单失败重试次数
  retry: 100
  # 查询库存请求超时(秒)，可选配置，默认30秒
  timeout: 30
  # 最大查询随机数，给查询请求加的随机间隔时间，默认5s
  random_time: 5
  # 默认UA
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
  # 是否使用随机 useragent，默认为 True
  random_useragent: True
  # 多进程数量
  work_count: 1

Account:
  # 支付密码
  # 如果你的账户中有可用的京券（注意不是东券）或 在上次购买订单中使用了京豆，
  # 那么京东可能会在下单时自动选择京券支付 或 自动勾选京豆支付。
  # 此时下单会要求输入六位数字的支付密码。请在下方配置你的支付密码，如 123456 。
  # 如果没有上述情况，下方请留空。
  payment_pwd: ""

Message:
  # 使用了Server酱的推送服务
  # 如果想开启下单成功后消息推送，则将 enable 设置为 true，默认为 false 不开启推送
  # 开启消息推送必须填入 sckey，如何获取请参考 http://sc.ftqq.com/3.version。感谢Server酱～
  enable: False
  sckey: "?????"



























#:============================:
#:============================:
#:=====:以下框架配置请勿动:======:
#:============================:
#:============================:

Information:
  project: JD SHOPPER
  version: 1.1.2
  author: Louis·Young
  time: 2021-07-27

Debug: # 调试设置（用于测试Core中代码）
  open: false # 开启Debug后无视Scheduler只会执行Core.core.main函数中代码

Server: # 服务器设置（用于提供静态文件和api）
  open: true # 是否启用服务器
  name: Turbon-Server # 服务器名
  version: 1.0.0-beta # 服务器版本
  port: 12021 # 运行端口号
  local_host: 0.0.0.0 # 用于启动项目的局域网IP
  server_host: localhost # 填写服务器域名
  process_mode: false # 是否开启多进程
  process_count: 4 # 进程数量
  static_path: /Static

GUI:
  # GUI Settings
  # 进行GUI打包时需要确保安装pywebview, 并手动取消GUI/gui.py下的注释
  open: False

Logger: # 日志设置（用于日志系统）
  file_name: jd-shopper.log # 日志文件名
  file_path: /Logger/Log_Files/ # 日志文件地址
  count: 1 # 日志文件个数
  max_bytes: 10485760 # 单个日志文件的大小
  clear_up: true # 每次启动程序是否清理日志文件中内容
  colorful: true  # 命令行色彩输出
  server_logger: false # 开启 Server 的详细日志记录

Storage: # 本地存储设置（用于状态持久化存储）
  name: state.json # 存储文件名
  path: /Storage/ # 存储地址

Depend: # 依赖管理模块（用于动态引入依赖库）
  open: true
  file: requirements.txt
  path: /

Scheduler: # 调度器设置（用于定时执行）
  open: false # 是否开启定时执行
  skip_weekend: true # 周末不执行任务
  time: # 任务执行时间
    - 18:00:00
    - 19:00:00
    - 20:00:00
